### ISSUE TITLE
Updating settings via CDI does not stick.

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/esp32olcbhub#23] opened 2020-12-13 01:18 UTC
The same from #21 happens when settings are updated via CDI.

Upon reboot, they are reset back to defaults.

**Comment by TrainzLuvr** [comment] 2020-12-13 01:21
Further to this, after closing and re-opening the CDI, all the settings are gone from the fields and the node cannot be rebooted by issuing the More/Reboot command.

It appears stuck processing RX packets (reboot is probably one of them).

**Comment by atanisoft** [comment] 2020-12-13 01:34
I've not seen the CDI entries not stick when using SPIFFS for storage. That is primarily why LittleFS is not enabled by default now.

The reboot issue I've seen as part of shutdown of the http server, I'll investigate that further as well. It is not consistently hanging there

**Comment by atanisoft** [comment] 2020-12-13 13:03
Closing as duplicate of #21. The latest code will allow disabling the factory reset and user buttons which will resolve the recreation of the config file on startup (due to floating factory reset pin, default also changed to 15 which has a P/U).

**Closed by atanisoft** 2020-12-13 13:03 UTC
