### ISSUE TITLE
Updating node config via JMRI CDI not reflected in apply_configuration

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/esp32olcbhub#7] opened 2020-11-07 01:03 UTC
Tried to enable Hub from CDI and change TXPower, but the config did not persist upon reboot.

**Comment by atanisoft** [comment] 2020-11-07 01:18
I've reproduced this but can not narrow down the cause, it appears that when JMRI sends the data to the node it doesn't actually write the data. Set [this](https://github.com/atanisoft/OpenMRNIDF/blob/main/src/freertos_drivers/esp32/Esp32WiFiManager.cpp#L288-L294) line to use INFO instead of VERBOSE and you can see that the freshly loaded config is identical. I'll be doing some digging into this soon.

**Comment by TrainzLuvr** [comment] 2020-11-07 01:20
I can't get to the Web interface without a working STA. :(

**Comment by atanisoft** [comment] 2020-11-07 01:26
> I can't get to the Web interface without a working STA. :(

Pull the latest code, update `constants.hxx` to set your SSID/PW for Station and then add:
```
config.force_reset = true;
```
on [this](https://github.com/atanisoft/esp32olcbhub/blob/main/main/esp32olcbhub.cpp#L236) line.

**Comment by TrainzLuvr** [comment] 2020-11-07 01:39
I'm seeing this:

```
[WiFi] [2/36] Waiting for SSID connection.
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:12 (pending:12,suc:0,fail:0) bus (arb-err:0,err:0,state:Running)
[WiFi] [3/36] Waiting for SSID connection.
[WiFi] Connection failed, reconnecting to SSID: ***** (reason:204).
[WiFi] Connection failed, reconnecting to SSID: ***** (reason:205).
[WiFi] [4/36] Waiting for SSID connection.
[WiFi] Connection failed, reconnecting to SSID: ***** (reason:2).
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:12 (pending:12,suc:0,fail:0) bus (arb-err:0,err:0,state:Running)
[WiFi] [5/36] Waiting for SSID connection.
[WiFi] Connection failed, reconnecting to SSID: ***** (reason:205).
```
Seems like a race condition?

I reset a few times and eventually connects, but I think that's not reliable because in production there would be no serial monitor, unless people connect a OLED display to I2C.

**Comment by TrainzLuvr** [comment] 2020-11-07 01:43
It's also telling me wrong password when I enter "esp32olcbhub".

I think it's using the STA password instead again?

**Comment by atanisoft** [comment] 2020-11-07 01:45
> Seems like a race condition?

It's likely power supply related. I'm seeing a similar issue when powering via USB *AND* powering the CAN transceiver via the 5v pin. If I disconnect the CAN power until after WiFi connects it is fine.

> I think that's not reliable because in production there would be no serial monitor

It also wouldn't be powered via USB :) I can create a PCB that powers it from the OpenLCB bus possibly but it may draw 200mA or more.

> It's also telling me wrong password when I enter "esp32olcbhub".
> 
> I think it's using the STA password instead again?

It should be using whatever you have entered in `constants.hxx` for `DEFAULT_AP_NAME` / `DEFAULT_AP_PASS`.

**Comment by TrainzLuvr** [comment] 2020-11-07 01:48
I'm connected via USB but there are no other peripherals connected since I'm still flashing the board.

I was looking at these changes  https://github.com/atanisoft/esp32olcbhub/commit/66fb56b66f4bd59296d9ff54757bca0d97f32c1c and I think the issue might be that you need to also account for WIFI_MODE_APSTA, as a separate option from _AP and _STA, where both DEFAULT_AP_PASS and DEFAULT_STA_PASS are set, but are different.

**Comment by atanisoft** [comment] 2020-11-07 01:51
> both DEFAULT_AP_PASS and DEFAULT_STA_PASS are set, but are obviously different.

Both are passed into `Esp32WiFiManager` today, the first two parameters are for STA unless mode is AP.

**Comment by TrainzLuvr** [comment] 2020-11-07 01:53
Yes but what if the mode is APSTA, then it needs to check the AP password (inbound) and not STA one (outbound).

**Comment by atanisoft** [comment] 2020-11-07 02:00
> Yes but what if the mode is APSTA, then it needs to check the AP password (inbound) and not STA one (outbound).

In that case it will verify if the MODE != AP and sta_ssid == blank. If both of those evaluate to true it will revert to SoftAP only mode.

**Comment by TrainzLuvr** [comment] 2020-11-07 02:03
I recall that in my ESP32CS_barebone, this was not a problem...could you please take a look at the similar ESP32CS code, maybe there's something slightly different there that makes the difference?

All I know is that it does not accept the AP password (esp32olcbhub) from the UWT-100, but instead it takes the STA password which is my home WiFi network pass, and a wrong one to use. :)

**Comment by atanisoft** [comment] 2020-11-07 02:06
> maybe there's something slightly different there that makes the difference?

The only difference is the storage in NVS which seems to be corrupt in your case. I'd suggest update `constants.hxx`, `idf.py erase_flash; idf.py build flash monitor`. Possibly even adding some debug log statements in `esp32olcbhub_stack.cpp` to print out the values being passed in to ensure 100% they are correct.

**Comment by TrainzLuvr** [comment] 2020-11-07 02:10
I actually did that beforehand, constants.hxx has WIFI_MODE_APSTA, and the appropriate networks and passwords are set.

I did erase_flash and then flash afterwards...it connects to my home WiFi and creates a hotspot but the throttle does not connect with the hotspot password.

**Comment by atanisoft** [comment] 2020-11-07 02:21
I'll do some testing but I haven't encountered that before.

**Comment by TrainzLuvr** [comment] 2020-11-07 03:01
I've erased flash, flashed firmware, and still not accepting the AP password.

I'm out of ideas here...

**Comment by TrainzLuvr** [comment] 2020-11-07 03:31
I got it to work by altering the code https://github.com/atanisoft/esp32olcbhub/blob/66fb56b66f4bd59296d9ff54757bca0d97f32c1c/main/esp32olcbhub_stack.cpp#L78-L88 so it resembles the ESP32CommandStation https://github.com/atanisoft/ESP32CommandStation/blob/667de7e897666b52bef308f1bffa54cba94c6b4a/components/Configuration/LCCWiFiManager.cpp#L198-L201

Basically the AP appears to be running in the Open mode without a password. Although in the ESP32CS, password and SSID for both AP and STA were being set to the same values earlier in the code (esp32cs).

**Comment by TrainzLuvr** [comment] 2020-11-07 03:43
Unfortunately, the same behaviour repeats here like in ESP32CS...

```
[TWAI] RX:682 (pending:0,overrun:89,discard:0) TX:934 (pending:0,suc:934,fail:0) bus (arb-err:220,err:0,state:Running)
[TWAI] RX:688 (pending:0,overrun:89,discard:0) TX:936 (pending:0,suc:936,fail:0) bus (arb-err:220,err:0,state:Running)
[TWAI] RX:729 (pending:0,overrun:123,discard:0) TX:1008 (pending:0,suc:1008,fail:0) bus (arb-err:254,err:0,state:Running)
[HealthMon 00:12:30] Free heap: 162.70kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 2.60kB
[TWAI] RX:729 (pending:0,overrun:123,discard:0) TX:1008 (pending:0,suc:1008,fail:0) bus (arb-err:254,err:0,state:Running)
[TWAI] RX:729 (pending:0,overrun:123,discard:0) TX:1008 (pending:0,suc:1008,fail:0) bus (arb-err:254,err:0,state:Running)
[TWAI] RX:729 (pending:0,overrun:123,discard:0) TX:1008 (pending:0,suc:1008,fail:0) bus (arb-err:254,err:0,state:Running)
[HealthMon 00:14:00] Free heap: 162.70kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 2.60kB
[TWAI] RX:729 (pending:0,overrun:123,discard:0) TX:1008 (pending:0,suc:1008,fail:0) bus (arb-err:254,err:0,state:Running)
[TWAI] RX:729 (pending:0,overrun:123,discard:0) TX:1008 (pending:0,suc:1008,fail:0) bus (arb-err:254,err:0,state:Running)
```
It literally hung my Configure Nodes window in JMRI when I clicked Refresh and all nodes disappeared. I closed and re-opened the window, but clicking Refresh causes all nodes to disappear again. JMRI is really confused it seems, maybe it's a bug in it as well. :)

**Comment by atanisoft** [comment] 2020-11-07 13:13
> I've erased flash, flashed firmware, and still not accepting the AP password.

As you found by switching to the CS style (where it does use the same PW for STA and AP) there is a bug in the `Esp32WiFiManager` code. I'll be looking at fixing that today.

> Unfortunately, the same behaviour repeats here like in ESP32CS..

I'll do some digging, I have a few ideas to test on this lighter codebase which may alleviate the overruns. I don't know that I can do anything about the arb-err as it looks like the nodes are trying to talk simultaneously and that will result in arb-err increases but shouldn't result in the node disappearing. We will need to enable a packet capture and see what is happening.

**Comment by atanisoft** [comment] 2020-11-07 15:42
Cleaned up comments that were not related to CDI and moved the bug for SoftAP PW to https://github.com/atanisoft/OpenMRNIDF/issues/2.

**Comment by atanisoft** [comment] 2020-11-07 20:59
Packet capture:
```
[TWAI] RX:199 (pending:0,overrun:0,discard:0) TX:835 (pending:0,suc:835,fail:0) bus (arb-err:0,err:0,state:Running)
[HealthMon 00:00:30] Free heap: 190.00kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 2.57kB
:X1A809072N20010000008601;
:X19A28809N007280;
:X1A072809N201100000086;
:X19A28072N0809;
```
The above is setting the "Hub Enable" selector to Yes and clicking Write.

```
[TWAI] RX:201 (pending:1,overrun:0,discard:0) TX:837 (pending:0,suc:837,fail:0) bus (arb-err:0,err:0,state:Running)
Esp32WiFiManager::apply_configuration(4, 0)
Esp32WiFiManager: uplink:Yes (auto:_openlcb-can._tcp, manual::12021) tx:78 sleep:No hub:No (_openlcb-can._tcp:12021)
:X1A809072N20A8;
:X19A28809N007200;
```
The above is closing the dialog.

**Comment by atanisoft** [comment] 2020-11-08 11:05
Ok, JMRI is not at fault for this one. OpenMRN opens the node config file twice, one handle is used by MemoryConfig (CDI config access) and the other by ConfigListener instances. Normally the underlying filesystem will sync on write but LittleFS is caching data until file close or fsync being called explicitly.

https://github.com/bakerstu/openmrn/issues/398 was filed for the stack opening the config file multiple times. I'll investigate if there is a quick fix via LittleFS as this will be an option in arduino-esp32 2.0.0 which is planned for once ESP-IDF v4.2 is stable.

**Comment by atanisoft** [comment] 2020-11-08 13:31
Filed https://github.com/joltwallet/esp_littlefs/issues/18 as well to see if there are any options we can use to alter this caching behavior.

**Comment by TrainzLuvr** [comment] 2020-11-10 22:20
Went to see if the update via CDI worked, and I got this trying to open the configuration window:

```
[TWAI] RX:248 (pending:0,overrun:0,discard:0) TX:91 (pending:1,suc:90,fail:0) bus (arb-err:0,err:0,state:Running)
[TWAI] RX:537 (pending:0,overrun:0,discard:0) TX:91 (pending:1,suc:90,fail:0) bus (arb-err:0,err:0,state:Running)
[TWAI] RX:610 (pending:0,overrun:0,discard:0) TX:110 (pending:1,suc:109,fail:0) bus (arb-err:45,err:1,state:Running)
[HealthMon 00:11:00] Free heap: 172.73kB (max block size: 106.41kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 1.22kB
CanDatagramWriteFlow: No datagram response arrived from destination 000000000000.
MemoryConfig: Failed to send response datagram. error code 81000
[TWAI] RX:611 (pending:0,overrun:0,discard:0) TX:120 (pending:1,suc:119,fail:0) bus (arb-err:45,err:1,state:Running)
[TWAI] RX:611 (pending:0,overrun:0,discard:0) TX:120 (pending:1,suc:119,fail:0) bus (arb-err:45,err:1,state:Running)
```

After clicking on  Re-try it finally opened, but not sure why it hung the first time.

**Comment by atanisoft** [comment] 2020-11-10 22:24
I've seen this a few times when working with JMRI, often it is a frame that didn't get ack'd in time. It's possible there is an error being hit during TX that causes the frame to be dropped and JMRI gives up on first error (it would be nice to have retries built in for reliability).

**Comment by TrainzLuvr** [comment] 2020-11-10 22:25
Uh oh, so I went to change a value, wrote it, then More...->Update Complete and More...->Reboot and boom:

```
Shutdown listening socket 12021.
[mDNS] Removing advertisement of _openlcb-can._tcp.
[Uplink] Disconnecting from uplink.
Guru Meditation Error: Core  0 panic'ed (Interrupt wdt timeout on CPU0). 

Core  0 register dump:
PC      : 0x40089914  PS      : 0x00060b34  A0      : 0x800884d9  A1      : 0x3ffc8460  
A2      : 0x3ffc08a4  A3      : 0x3ffc8658  A4      : 0x00000ca3  A5      : 0x3f4068b6  
A6      : 0x00000001  A7      : 0x3ffd59c4  A8      : 0x3ffc8658  A9      : 0x00000008  
A10     : 0x3ffc8658  A11     : 0x00000008  A12     : 0x00060b23  A13     : 0x00060b23  
A14     : 0x00000001  A15     : 0x00000001  SAR     : 0x00000008  EXCCAUSE: 0x00000005  
EXCVADDR: 0x00000000  LBEG    : 0x4000142d  LEND    : 0x4000143a  LCOUNT  : 0xffffffde  

Backtrace:0x40089911:0x3ffc8460 0x400884d6:0x3ffc8480 0x40089f5c:0x3ffc84a0 0x400d72c5:0x3ffc84e0 0x400f03d3:0x3ffc8500 0x400f12f5:0x3ffc8530 0x400f15f9:0x3ffc8560 0x400f5441:0x3ffc8580 0x400fa9a3:0x3ffc85a0
Core  1 register dump:
PC      : 0x400882fa  PS      : 0x00060034  A0      : 0x400877bf  A1      : 0x3ffbec10  
A2      : 0x00000000  A3      : 0x00050023  A4      : 0x0000cdcd  A5      : 0xb33fffff  
A6      : 0x0000cdcd  A7      : 0x0000abab  A8      : 0x3ffb116c  A9      : 0x00060023  
A10     : 0x00000000  A11     : 0x3f406992  A12     : 0x00000014  A13     : 0x3ffb0d10  
A14     : 0x3ffb0d58  A15     : 0x00000001  SAR     : 0x00000000  EXCCAUSE: 0x00000005  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace:0x400882f7:0x3ffbec10 0x400877bc:0x3ffbec30 0x40087772:0xa5a5a5a5 |<-CORRUPTED

Core 0:
stack :
0:  0x400884d6: vTaskPlaceOnEventList at C:/espressif/esp-idf/components/freertos/tasks.c:2905 (discriminator 2)
0:  0x40089f5c: xQueueGenericReceive at C:/espressif/esp-idf/components/freertos/queue.c:1595
0:  0x400d72c5: os_mutex_lock at r:\code\esp32olcbhub\build/../components/OpenMRNLite/src/os/os.h:551
  \-> inlined by: OSMutexLock::OSMutexLock(OSMutex*) at r:\code\esp32olcbhub\build/../components/OpenMRNLite/src/os/OS.hxx:499
0:  0x400f03d3: ActiveTimers::update_timer(Timer*) at r:\code\esp32olcbhub\build/../components/OpenMRNLite/src/executor/Timer.cpp:176
0:  0x400f12f5: SocketClient::shutdown() at r:\code\esp32olcbhub\build/../components/OpenMRNLite/src/executor/Timer.hxx:236
  \-> inlined by: ?? at r:\code\esp32olcbhub\build/../components/OpenMRNLite/src/executor/Timer.hxx:242
  \-> inlined by: ?? at r:\code\esp32olcbhub\build/../components/OpenMRNLite/src/utils/SocketClient.hxx:209
  \-> inlined by: SocketClient::shutdown() at r:\code\esp32olcbhub\build/../components/OpenMRNLite/src/utils/SocketClient.hxx:162
0:  0x400f15f9: openmrn_arduino::Esp32WiFiManager::stop_uplink() at r:\code\esp32olcbhub\build/../components/OpenMRNLite/src/freertos_drivers/esp32/Esp32WiFiManager.cpp:908
  \-> inlined by: openmrn_arduino::Esp32WiFiManager::stop_uplink() at r:\code\esp32olcbhub\build/../components/OpenMRNLite/src/freertos_drivers/esp32/Esp32WiFiManager.cpp:903
0:  0x400f5441: openmrn_arduino::Esp32WiFiManager::wifi_manager_task(void*) at r:\code\esp32olcbhub\build/../components/OpenMRNLite/src/freertos_drivers/esp32/Esp32WiFiManager.cpp:816
0:  0x400fa9a3: os_thread_start at r:\code\esp32olcbhub\build/../components/OpenMRNLite/src/os/os.c:391

Core 1
stack:
0:  0x400877bc: _frxt_dispatch at C:/espressif/esp-idf/components/freertos/xtensa/portasm.S:431
0:  0x40087772: _frxt_int_exit at C:/espressif/esp-idf/components/freertos/xtensa/portasm.S:231
```

**Comment by atanisoft** [comment] 2020-11-10 22:38
I've pushed that backtrace to it's own issue for tracking. It appears to be a race condition of sorts in the Timer code that I haven't been able to reproduce reliably enough to fix.

**Closed** 2020-11-12 14:38 UTC
Labels: bug
